name: Hello world

on:
  workflow_dispatch: 
  schedule:
    - cron: '*/10 * * * *' 

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: "echo 'hello world'"

  A:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Job A task
        run: echo "This is job A, running after hello-world-job"

  B:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Job B task
        run: echo "This is job B, running after hello-world-job"
